### ISSUE TITLE
bfv中缺少MKIII(S) Elite Combat Dagger资源

### ISSUE THREAD

**Issue by ececleon** [half-ghost/bf_record_search#1]

**Comment by ececleon** [comment]
The Unexpected Gift这个资源也没有

**Comment by half-ghost** [comment]
是缺少了这些武器的数据（击杀数，精准度等数据）还是说缺少图片资源，如果缺少了数据的话，那这个没办法，因为这个api给到的数据有些会缺少，比如战地1的维和者，波顿等，确实是在这个api里找不到数据。如果是缺少图片资源的话，请告诉我，我会再调试一下看看是不是我下载少了资源

**Comment by half-ghost** [comment]
> The Unexpected Gift这个资源也没有
是缺少了这些武器的数据（击杀数，精准度等数据）还是说缺少图片资源，如果缺少了数据的话，那这个没办法，因为这个api给到的数据有些会缺少，比如战地1的维和者，波顿等，确实是在这个api里找不到数据。如果是缺少图片资源的话，请告诉我，我会再调试一下看看是不是我下载少了资源

**Comment by ececleon** [comment]
两个都是缺少图片资源

**Comment by half-ghost** [comment]
> 两个都是缺少图片资源

好，我调试一下

**Comment by ececleon** [comment]
有没有网页可以用于提取资源

**Comment by half-ghost** [comment]
> 有没有网页可以用于提取资源

有的，我在源码中有写了下载图片的函数，如果你能读懂代码的话，可以自己调用下载

**Comment by half-ghost** [comment]
> 有没有网页可以用于提取资源

噢网页也在代码里写了

**Comment by half-ghost** [comment]
> 有没有网页可以用于提取资源

我看了一下，好像战地5这个查询api有点问题，似乎不同账号给出的数据不一样，不同账号的武器啊载具啊数据的条数是不一样的，我图片是以这个api给出的数据来下载的，而我写的时候只用了一个账号作为测试，所以导致github上放出的图片资源不全。等我这段时间再修改修改

**Comment by ececleon** [comment]
我感觉都是一些限定武器的图没有

**Comment by ececleon** [comment]
可惜battlelog关了,不然应该可以直接从上面扒资源

**Comment by half-ghost** [comment]
> 我感觉都是一些限定武器的图没有

战地1确实是限定武器和彩蛋武器没有数据，但是战地5我刚刚测了几个id了，确实是不同id有不同数量的数据

**Comment by half-ghost** [comment]
搞定了，你更新一下看看，只需要更新bf1search文件就可以了

**Comment by ececleon** [comment]
好的我试试

**Comment by ececleon** [comment]
好了，缺少图片能正常触发补全图片功能

**Comment by half-ghost** [comment]
好的，那我关闭这个issue了，有啥问题再开一个吧
