### ISSUE TITLE
很开心 有人用到gametools 的api前来考古

### ISSUE THREAD

**Issue by SoraKasvgano** [half-ghost/bf_record_search#3]
很开心 有人用到gametools 的api前来考古

另外 联ban因为一个QQbot开发人员动用权限全亚服封禁一个无辜玩家（且不是第一次），而且还背刺师父已经解散，为了防止有些人继续为非作歹，所以 我们已经开放了战地1服管相关原生API，欢迎继续造轮子。

https://t.bilibili.com/627727784060794920

**Comment by half-ghost** [comment]
感谢提供的信息，不过这可能要等到我哪个时候有时间重构这个插件时才能派上用场了

**Comment by half-ghost** [comment]
您好，最近在重构这个插件了，已经完成绝大部分的重构，但是有时候gametools不是很稳定，并且次数挺多的，导致发出去的请求总是断掉，我不太确定是自己服务器网络问题，还是说这个api网站的问题，所以在考虑用战地原生的api，于是乎现在有个问题想向您请教一下，就是网络方面的gametools和原生的api，哪个更稳定一些，因为我还没开始试着使用原生的，所以如果您知道的话烦请告诉我一下，我也可以省去试错的时间，如果不知道也没事，我后边自己再去琢磨琢磨，谢谢！
